spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${CHAT_FLOW_DB_URL:jdbc:mysql://127.0.0.1:3306/gijela_chat_flow?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true}
      username: ${CHAT_FLOW_DB_USERNAME:root}
      password: ${CHAT_FLOW_DB_PASSWORD:secretmysql}
      initial-size: 2
      max-active: 20
      min-idle: 2
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
